# Generated by Django 4.0.6 on 2022-09-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_slider_competitionattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='reg_fee',
        ),
        migrations.AlterField(
            model_name='competitionattribute',
            name='reg_fee',
            field=models.PositiveIntegerField(),
        ),
    ]
