# Generated by Django 4.1 on 2022-09-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_competition_reg_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': '3. Branches'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '2. Categories'},
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name_plural': '6. Competitions'},
        ),
        migrations.AlterModelOptions(
            name='competitionattribute',
            options={'verbose_name_plural': '7. CompetitionAttribute'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name_plural': '5. Domains'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '1. sliders'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'verbose_name_plural': '4. Years'},
        ),
    ]
