# Generated by Django 4.0.6 on 2022-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_competition_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(upload_to='slider_imgs'),
        ),
    ]
